# Configurations
title:            Bookkeeping
#longtitle:        
author:           mcc
email:            mcurcio@duck.com
#description: >
#  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

# commented out for testing
#baseurl: ""
#url: "https://mcc-us.github.io/bookkeeping"

# _config.yml for bookkeeping sitel, suggested by Gemini!

baseurl: https://mcc-us.github.io/bookkeeping
url: 

rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /bookkeeping/assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

site.github_username: mcc-us
# Just added to see if this fixes the github link on the home page

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 1000px

destination:      ./_site
incremental:      true
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
